tap "homebrew/bundle"
tap "homebrew/cask-fonts"
tap "homebrew/core"

brew "fzf"
brew "neovim"
brew "nodebrew"
brew "rbenv"
brew "tmux"
brew "zsh"

cask "font-hackgen"
cask "font-hackgen-nerd"
cask "hammerspoon"
cask "alacritty"
cask "iterm2"
cask "bitwarden"
cask "raycast"
